### ISSUE TITLE
Users who register with an invitation code can't see lists/cards

### ISSUE THREAD

**Issue by brend** [wekan/wekan#1610]
## Issue

**Server Setup Information**:

* Operating System: Ubuntu 16.04.4 x64
* Deployment Method(snap/sandstorm/mongodb bundle): manual installation
* Node Version: v8.9.1
* MongoDB Version: 3.2.19
* Wekan Version: 0.85.0
* ROOT_URL='http://\<local ip\>:8000/'

**Problem description**:

Users who register with an invitation code can enter boards, but can't see lists/swimlanes/cards. The board appears blank (gray).

**Comment by brend** [comment]
The issue appears to be due to a missing _profile.boardView_ property in the mongodb user document. The button to switch board views in Wekan shows the word "undefined", and clicking on it has no effect. After inserting the _profile.boardView_ property and setting it to "board-view-lists", the user can see lists and cards normally, and the board view switch button works.

**Comment by xet7** [comment]
At beginning users only see their own Welcome board. You need to add users to shared boards.

Also check that your [root-url settings are correct](https://github.com/wekan/wekan/releases)

**Comment by brend** [comment]
I've updated the original post with the ROOT_URL setting. 

Users can browse and create boards and open them, but the board contents are not visible, even those of the boards they created themselves.

![board browser 2](https://user-images.githubusercontent.com/472970/39361801-4aca2b62-4a24-11e8-9064-eb5e53c74ce3.PNG)
![board view](https://user-images.githubusercontent.com/472970/39361802-4aefa662-4a24-11e8-8e5f-12c4d4d976bd.PNG)

**Comment by xet7** [comment]
Did you add this setting for Wekan?
```
port='8000'
```

**Comment by xet7** [comment]
How did you install Wekan manually?

**Comment by brend** [comment]
I have added an environment variable `PORT=8000`; is that what you mean?

I downloaded the [Meteor.js precompiled bundle](https://releases.wekan.team/wekan-0.85.tar.gz) and followed this [installation guide](https://www.howtoforge.com/tutorial/ubuntu-wekan-installation/).

**Comment by brend** [comment]
By the way, this issue only seems to affect users registered by invitation code. Users who register without an invitation code do not experience this issue.

**Comment by xet7** [comment]
I have not made that installation guide.

All installation guides are here:
https://github.com/wekan/wekan/releases

I would really recommend using snap, it's fastest to install.

**Comment by andresmanelli** [comment]
@brend you are totally right I think. When creating a user from the register form, the profile object is created but no `boardView` is added to that objet. The `autoValue` method is not called because the profile object exists.

I think the code below should fix this (**not tested**):

```diff
--- a/models/users.js
+++ b/models/users.js
@@ -495,6 +495,7 @@ if (Meteor.isServer) {
       throw new Meteor.Error('error-invitation-code-not-exist', 'The invitation code doesn\'t exist');
     } else {
       user.profile = {icode: options.profile.invitationcode};
+      user.profile.boardView = 'board-view-lists';
     }
 
     return user;
```

**Comment by xet7** [comment]
@andresmanelli 

I did not yet get that code working, you could test it more.

**Comment by xet7** [comment]
Hmm, I'll include this just for testing. Maybe I'm just not testing it correctly.

**Comment by simopaasisalo** [comment]
Can confirm this, I had the same issue but adding profile.boardView = 'board-view-lists' to the database allowed the user to see the contents again

**Comment by xet7** [comment]
@brend @simopaasisalo 

Is this fixed now?

**Comment by xet7** [comment]
I did include this is latest release v0.92

**Comment by robisonr** [comment]
As of v0.95 this is still an issue for accounts that were already having the problem. Not sure if it resolves the issue for new accounts.

**Comment by xet7** [comment]
@robisonr 

Added to where? That line is already at Wekan v0.95:
https://github.com/wekan/wekan/blob/devel/models/users.js#L498

What version are you running?

Could someone please verify is this still a problem still in latest Wekan?

**Comment by robisonr** [comment]
We upgraded to v0.95 yesterday after already having the issue with users not seeing cards after signing up with a registration code. They were still unable to see cards after the upgrade and logging out and back in. We then went in and manually added the line in the database and they were able to see cards.

**Comment by xet7** [comment]
@robisonr 

What addition you made to database?

**Comment by robisonr** [comment]
On MongoDB inserting inserting the profile.boardView property and setting it to "board-view-lists".

**Comment by xet7** [comment]
Does @andresmanelli or somebody other have time to make pull request, that inserts profile.boardView property and setting it to "board-view-lists" ? So it does not need to be set manually? I'm currently busy with other unrelated work.

**Comment by brend** [comment]
I just updated our Wekan to version 1.01.0 and can confirm that the issue has been resolved. Users who join by invitation code are able to see and participate in boards.

**Comment by d3dbit** [comment]
Hello all,
Sorry, but I have just upgraded to v1.01 and I am continuing with the same issue.

![image](https://user-images.githubusercontent.com/26925243/40558787-cad33eca-6054-11e8-8f96-dec37f5ea1c3.png)
