### ISSUE TITLE
Card was selected as parent card (circular reference) and now board can be not opened anymore

### ISSUE THREAD

**Issue by MelBourbon** [wekan/wekan#2202]
## Issue
**Server Setup Information**:
* Did you test in newest Wekan?: Yes
* Wekan version: v.2.25.0
* Operating System: Ubuntu
* Deployment Method(snap/docker/sandstorm/mongodb bundle/source): Snap
* Http frontend if any: Nginx
* Node Version: v8.15.0

**Problem description**:
User wanted to select a parent card (unsure if correct term, user interface is German, so hopefully this translates well) and accidentally selected as parent the same card he wanted to change. This created a circular reference and the board does not load anymore or cannot accessed anymore.

Creating a circular reference should not be possible by setup or create a warning.

**Instructions to reproduce:**

Step 1:
![1](https://user-images.githubusercontent.com/30600002/53346909-4b7d1e00-3918-11e9-83f1-ddea0ad70863.png)

Step 2:
![2](https://user-images.githubusercontent.com/30600002/53346923-4fa93b80-3918-11e9-8592-c0c852baa3fe.png)

Step 3:
![3](https://user-images.githubusercontent.com/30600002/53346931-53d55900-3918-11e9-888f-4f3c9ff79e3c.png)

**Comment by xet7** [comment]
@MelBourbon 

When you ssh to Wekan server, what does this command show?
```
sudo snap logs wekan.wekan
```

**Comment by MelBourbon** [comment]
This is the output. Please note, I have hourly backups available and restored one of these to resolve issue. But log time may be from the time the issue occurred.

```
2019-02-25T13:39:21Z wekan.wekan[3490]:     at Array.forEach (<anonymous>)
2019-02-25T13:39:21Z wekan.wekan[3490]:     at Function._.each._.forEach (packages/underscore.js:139:11)
2019-02-25T13:39:21Z wekan.wekan[3490]:     at after (packages/matb33_collection-hooks.js:572:9)
2019-02-25T13:39:21Z wekan.wekan[3490]:     at Object.<anonymous> (packages/matb33_collection-hooks.js:588:5)
2019-02-25T13:39:21Z wekan.wekan[3490]:     at Object.collection.(anonymous function) [as remove] (packages/matb33_collection-hooks.js:146:21)
2019-02-25T13:39:21Z wekan.wekan[3490]:     at ns.Collection.CollectionPrototype._validatedRemove (packages/allow-deny/allow-deny.js:406:34)
2019-02-25T13:39:21Z wekan.wekan[3490]:     at DDPCommon.MethodInvocation.m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
2019-02-25T13:39:21Z wekan.wekan[3490]:     at packages/check.js:128:16
2019-02-25T13:39:21Z wekan.wekan[3490]:     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1186:15)
2019-02-25T13:39:21Z wekan.wekan[3490]:     at Object._failIfArgumentsAreNotAllChecked (packages/check.js:127:41)
```

**Comment by xet7** [comment]
@MelBourbon 

Can you for a moment change your Wekan language to English, and take screenshots, add arrows to screenshots showing what you did to make this circular reference, and add those screenshots directory to attachments to this issue comment? Because I did not understand it well enough from your description above. Thanks!

**Comment by MelBourbon** [comment]
Sure, see below. So in summary the "Test Card 3" was selected as parent for the identical card "Test Card 3"

Step 1:
![1](https://user-images.githubusercontent.com/30600002/53343389-9a26ba00-3910-11e9-9590-afc20a48d995.png)

Step 2:
![2](https://user-images.githubusercontent.com/30600002/53343392-9bf07d80-3910-11e9-8439-0a9888a5df1a.png)

Step 3:
![3](https://user-images.githubusercontent.com/30600002/53343496-ca6e5880-3910-11e9-95e8-d4d645dab3a2.png)

**Comment by MelBourbon** [comment]
@xet7 Added to the first comment of the issue.

**Comment by xarinatan** [comment]
I did the same thing with a Sandstorm grain, for me the result is that the page hangs and the browser complaining about Javascript hanging (Firefox). 
I in my infinite wisdom also kind of don't have a backup for this semi-important grain :dancer: would it be possible to run wait for the patch if that could undo the problem? otherwise I might have to mess with mongodb/wiredtigerdb to undo what I did :P

**Comment by xet7** [comment]
@xarinatan 

Most likely fix would include be removing all circular references, so easiest would be for you to just wait it to be fixed. There has been many bugs fixes today by many Wekan contributors, those will be included in next release, but today there were not enough time to fix this bug yet.

**Comment by xarinatan** [comment]
@xet7 sounds good to me, I've gotten it back to life at least, will wait for that release so I can use those cards again :+1: 
Thanks for the quick response!

**Comment by xet7** [comment]
@andresmanelli 

When I tried your circular changes, previous menu change and the new migration for fixing existing circulars that is not yet in Wekan release:
- Migration to fix circular bug did work once to make opening card possible
- After that, it was still possible to select card itself from menus to make circular bug happen again. This did make Standalone and Sandstorm Wekan to freeze, requiring Wekan/Sandstorm stop/start.
- After that, trying to open card still made Wekan/Sandstorm freeze.

I think fix would need to run every time at beginning of opening board.
And try to hide option to select card itself.

**Comment by andresmanelli** [comment]
This should be fixed now in my edge branch

**Comment by andresmanelli** [comment]
@xet7 could you or any user check if this is fixed with https://github.com/wekan/wekan/commit/97822f35fd6365e5631c5488e8ee595f76ab4e34 ?

**Comment by xet7** [comment]
@andresmanelli 

Ok I will check, just a moment.

**Comment by xet7** [comment]
@andresmanelli 

This is not fixed on Sandstorm. When I click circular bug card, Sandstorm freezes, and requires restart of Sandstorm.

**Comment by xet7** [comment]
@andresmanelli 

It seems that on Sandstorm I am unable make new circular happen by selecting card itself, because card itself is not in menu.

**Comment by xet7** [comment]
@andresmanelli 

So it seems that only remainin issue is that old circulars are not removed automatically.

**Comment by xarinatan** [comment]
@xet7 @andresmanelli would it perhaps be possible to one-time check for existing circular references when an upgrade script is ran when upgrading the database/metadata to the next version (if there is any, I'm not that familiar with the internals of wekan)? That way you wouldn't have to e.g do an expensive check for it every time the board is loaded, as well as catering to existing users who have still have the problem from an older version.

**Comment by xet7** [comment]
@xarinatan 

There will be renaming of migrations from @andresmanelli so that removing circular would work once more.

**Comment by andresmanelli** [comment]
Created https://github.com/wekan/wekan/pull/2248

**Comment by MelBourbon** [comment]
In v.2.45 (SNAP) I can now not select any parent card. None is shown as selection even if cards are existing.

![image](https://user-images.githubusercontent.com/30600002/54191664-ad13bf80-44b6-11e9-83b7-ef0d1a860710.png)

**Comment by eksell** [comment]
Got this bug in Wekan ver. 4.47
Two cards referencing eachother as parent - this in turn makes the whole Wekan board hang in fullscreenmode. 
If i reduce window size so that it load in mobile mode the board will load but clicking either of the two lists that each contain one of the mentioned cards make it hang again.
I've also tried opening the cards directly with URL-references with the same result.
