### ISSUE TITLE
"Invalid Email" Error

### ISSUE THREAD

**Issue by nickian** [wekan/wekan#3134]
I'm using the latest Snap version. I know 100% that my SMTP information is correct. When I click to send a test email, I just get a browser alert saying "Invalid email." What is this error referring to? The email set in my user profile, or the email set in the SMTP settings? Is there a more detailed error log somewhere?

I'm not sure if this is related, but another thing I noticed: As an admin user, and with the setting for "Allow Email Change" set to yes, I am not able to edit my email address in the "edit profile" section of the user dropdown menu. It just displays a non-editable form field with the "readonly" attribute.

**Comment by marc1006** [comment]
I fixed a check, and that's probably why it's showing up now.... (see https://github.com/wekan/wekan/pull/3112/commits/6e088af3d13b3b5912b783b485681bbd44ea4427).

It depends on the email setting of the logged in user if I understand the code correctly.

**Comment by marc1006** [comment]
Here is a fix for it: https://github.com/wekan/wekan/pull/3135

**Comment by marc1006** [comment]
[snip...]

> 
> I'm not sure if this is related, but another thing I noticed: As an admin user, and with the setting for "Allow Email Change" set to yes, I am not able to edit my email address in the "edit profile" section of the user dropdown menu. It just displays a non-editable form field with the "readonly" attribute.

I don't know the semantics for an admin user, but to me this looks like another issue.

**Comment by nickian** [comment]
Ok, I can test when the next snap release is available to refresh.

I also noticed that when I change the SMTP info via the command line, those changes aren't reflected in the web admin UI. Should those be two methods be saving the values to the same place? Or does the CLI override the web UI settings?

I'm not receiving any email notifications, but I'm hoping it's related to this "invalid email" issue. I set up notifications like this:

```
snap set wekan bigevents-pattern='received|start|due|end'
snap set wekan notify-due-days-before-and-after='3,2,1,0,-1,-2,-3'
snap set wekan notify-due-at-hour-of-day='9'
```

**Comment by nickian** [comment]
The test email comes through now, but I'm still not receiving any actual email notifications from Wekan.

I have it configured like this:

```
snap set wekan mail-url='smtps://me@domain.com:PASSWORD@server.com:465'
snap set wekan bigevents-pattern='received|start|due|end'
snap set wekan notify-due-days-before-and-after='3,2,1,0,-1,-2,-3'
snap set wekan notify-due-at-hour-of-day='9'
```

Does the Snap command to set the `mail-url` do something different than the mail settings in the web UI? It appears that I can have totally different settings in both and when I update one it is not reflected in the other. Are they for two different things?

**Comment by marc1006** [comment]
AFAIK, you have to set the same mail configuration in both places. Please have a look https://github.com/wekan/wekan-snap/issues/107 and https://github.com/wekan/wekan/wiki/Troubleshooting-Mail.

**Comment by nickian** [comment]
It's not clear to me why there are two different settings for SMTP. Why can't we just save one configuration in the web UI, test it, and successfully have notifications? What's the point of the additional CLI settings?

Also, I noticed that in the web UI, when I have port 587 saved (which is for TLS, 465 is SSL), I get an error. However, if I uncheck "Enable TLS support for SMTP server," it works. I have to check the box if I'm using port 465. Isn't that backwards? I thought TLS was on port 587 and SSL was 465.

The notifications are still not coming through for me. I have the web UI settings set to this (and the test works):

**SMTP Host:** mail.myserver.com
**SMTP Port:** 587
**Username:** me@myserver.com
**Pass:** Password (it also has an exclaimation, not sure if that character can cause problems)
**TLS Support:** Unchecked
**From:** Boards <me@myserver.com>

This works fine when I hit the test button it comes through. On the CLI I have each of the following configs. None have worked:

```
snap set wekan mail-from='Boards <me@myserver.com>'
snap set wekan mail-url='smtps://me%40myserver.com:Password%21@mail.myserver.com:587'
```
I have also tried these:

```
snap set wekan mail-url='smtps://me%40myserver.com:Password%21@mail.myserver.com:587?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false'

snap set wekan mail-url='smtps://me%40myserver.com:Password%21@mail.myserver.com:587?ignoreTLS=false&tls={rejectUnauthorized:true}&secure=true'
```

Is there a setting I'm getting wrong?

Thanks for your help!

**Comment by marc1006** [comment]
> It's not clear to me why there are two different settings for SMTP. Why can't we just save one configuration in the web UI, test it, and successfully have notifications? What's the point of the additional CLI settings?

I don't know :/ To me, it looks like the code prefers the environment variable if set, otherwise it uses the settings from the database.

> 
> Also, I noticed that in the web UI, when I have port 587 saved (which is for TLS, 465 is SSL), I get an error. However, if I uncheck "Enable TLS support for SMTP server," it works. I have to check the box if I'm using port 465. Isn't that backwards? I thought TLS was on port 587 and SSL was 465.

You have to check "Enable TLS support for SMTP server" if the server requires TLS/SSL **AND DOES NOT** use STARTTLS. The description should in any case be improved. 

> 
> The notifications are still not coming through for me. I have the web UI settings set to this (and the test works):

Are there any errors on the console?

[...snip]

**Comment by xet7** [comment]
Well, there is a story:
1. Someone added Admin Panel and SMTP settings
2. Someone added environment variable SMTP settings
3. Because I did think having settings in Admin Panel is not necessary, I removed those settings from Admin Panel
4. But because someone asked that those Admin Panel settings should be added back, so I added them.
5. And there still is bugs in those settings, that get lost sometimes https://github.com/wekan/wekan-snap/issues/78
6. So this would require, that someone looks at the code, and creates a fix as a Pull Request

**Comment by nickian** [comment]
Sorry, I think was confusing TLS with STARTTLS. But I agree that the description could be more intuitive on that.

I don't see any errors in the browser console. Is there a different log I can look at or another way to troubleshoot this?

Is there a way to test the setting in the command line to make sure it is valid? If I update the setting, then create a new task with a due date, or make a comment with myself tagged, shouldn't I receive a notification?

**Comment by xet7** [comment]
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#example-aws-ses
