### ISSUE TITLE
Exception while invoking method 'inviteUserToBoard' Error: Is comment only is required

### ISSUE THREAD

**Issue by vampirefrog** [wekan/wekan#950]
in boards.js I've had to add 'isCommentOnly: true' around line 315, to get rid of this error. Not only that, but when inviting a user to a board, the only error I would receive was '400'

**Comment by rhelsing** [comment]
@vampirefrog I implemented the comment permissions feature but I am fairly new to meteor. I did not experience this issue when testing but I will try to fix it if you give me more details.. If the default level that a user should be at is normal when a user is invited, then isCommentOnly should be set to false instead.

**Comment by vampirefrog** [comment]
Sorry, I meant false indeed. Thanks for the quick fix

**Comment by xet7** [comment]
Merged. Will be included in next release.

**Comment by neooleg** [comment]
#rhelsing I have your hotfix (my revision is 823aea49), but the issue is still reproduces.

Do you need more details to investigate?

**Comment by rhelsing** [comment]
@xet7 would you recommend that I do something like in #970 to resolve this? Except with isCommentOnly?

**Comment by rhelsing** [comment]
@xet7 see above?

**Comment by Jean-Daniel** [comment]
Note that there is at least 2 places where user are created while importing Trello Boards.

The first one is at wekan/import.js:144

The second one at wekan/import.js:169

**Comment by rhelsing** [comment]
@Jean-Daniel thank you, are there any other spots I may have missed? Is there a callback or modification I can make at a higher level (on the user model maybe?) that would solve all of these potential issues? Something similar to #970
